name: Terraform Apply by Changed Directory

on:
  push:
    branches: [ main,dev ]
    paths:
      - 'v1-single-instance/env/dev/**'
      - 'v1-single-instance/env/prod/**'
      - 'v2-3-tier/env/dev/**'
      - 'v2-3-tier/env/prod/**'
  pull_request:
    branches: [ main,dev ]
    paths:
      - 'v1-single-instance/env/dev/**'
      - 'v1-single-instance/env/prod/**'
      - 'v2-3-tier/env/dev/**'
      - 'v2-3-tier/env/prod/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Detect changed environment
      id: detect
      uses: tj-actions/changed-files@v44
      with:
        files: |
          v1-single-instance/env/dev/**
          v1-single-instance/env/prod/**
          v2-3-tier/env/dev/**
          v2-3-tier/env/prod/**

    - name: Set which env to apply
      id: set-env
      run: |
        CHANGED=${{ steps.detect.outputs.all_changed_files }} 
        if echo "$CHANGED" | grep -q 'v1-single-instance/env/dev'; then
          echo "env_path=v1-single-instance/env/dev" >> $GITHUB_OUTPUT
        elif echo "$CHANGED" | grep -q 'v1-single-instance/env/prod'; then
          echo "env_path=v1-single-instance/env/prod" >> $GITHUB_OUTPUT
        elif echo "$CHANGED" | grep -q 'v2-3-tier/env/dev'; then
          echo "env_path=v2-3-tier/env/dev" >> $GITHUB_OUTPUT
        elif echo "$CHANGED" | grep -q 'v2-3-tier/env/prod'; then
          echo "env_path=v2-3-tier/env/prod" >> $GITHUB_OUTPUT
        else
          echo "env_path=" >> $GITHUB_OUTPUT
        fi

    - name: Skip if nothing changed
      if: steps.set-env.outputs.env_path == ''
      run: echo "No relevant environment changed, skipping workflow."

    - name: Setup Terraform
      if: steps.set-env.outputs.env_path != ''
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Authenticate to GCP
      if: steps.set-env.outputs.env_path != ''
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'


    - name: Create terraform.tfvars from Secrets
      if: steps.set-env.outputs.env_path != ''
      working-directory: ${{ steps.set-env.outputs.env_path }}
      run: |
        case "${{ steps.set-env.outputs.env_path }}" in
        v1-single-instance/env/dev)
            printf "%s\n" "${{ secrets.TFVARS_DEV }}" > terraform.tfvars
            ;;
        # v1-single-instance/env/prod)
        #     echo "${{ secrets.TFVARS_PROD }}" > terraform.tfvars
        #     ;;
        # v2-3-tier/env/dev)
        #     echo "${{ secrets.TFVARS_V2_DEV }}" > terraform.tfvars
        #     ;;
        # v2-3-tier/env/prod)
        #     echo "${{ secrets.TFVARS_V2_PROD }}" > terraform.tfvars
        #     ;;
        esac

    - name: Terraform Init
      if: steps.set-env.outputs.env_path != ''
      working-directory: ${{ steps.set-env.outputs.env_path }}
      run: terraform init -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" -backend-config="prefix=${{ steps.set-env.outputs.env_path }}/terraform.tfstate"

    - name: Terraform Plan
      if: steps.set-env.outputs.env_path != ''
      working-directory: ${{ steps.set-env.outputs.env_path }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && steps.set-env.outputs.env_path != ''
      working-directory: ${{ steps.set-env.outputs.env_path }}
      run: terraform apply -auto-approve tfplan
